# Code generated by Gemini 3.5 Flash
# Prompted by K. Martin to convert csv Microsoft CMT export to json
# 2026-07-29

import csv
import json
import os

def convert_csv_to_json(csv_filepath, json_filepath):
    """
    Converts a program CSV file to JSON format, ignoring 'Created' and 'Last Modified' columns.
    """
    # Define columns to ignore (compared in lowercase to avoid case-sensitivity issues)
    ignored_columns = {'created', 'last modified'}
    
    # Columns that represent integer numbers (for optional type conversion)
    integer_columns = {'DAY', 'Paper ID', 'Number of Files'}
    
    json_data = []
    
    try:
        # 'utf-8-sig' handles UTF-8 files with or without BOM signatures (common in Excel exports)
        with open(csv_filepath, mode='r', encoding='utf-8-sig') as csv_file:
            reader = csv.DictReader(csv_file)
            
            # Clean and strip whitespace from headers
            if reader.fieldnames:
                reader.fieldnames = [field.strip() for field in reader.fieldnames]
            
            for row in reader:
                cleaned_row = {}
                for key, val in row.items():
                    if not key:
                        continue
                    
                    stripped_key = key.strip()
                    
                    # Ignore the specified columns
                    if stripped_key.lower() in ignored_columns:
                        continue
                    
                    # Strip surrounding whitespace from the values
                    cleaned_val = val.strip() if val is not None else ""
                    
                    # Optionally convert numeric fields to integers where possible
                    if stripped_key in integer_columns:
                        try:
                            cleaned_val = int(cleaned_val)
                        except ValueError:
                            # If conversion fails (e.g., empty string or invalid number), leave as string
                            pass
                    
                    cleaned_row[stripped_key] = cleaned_val
                
                json_data.append(cleaned_row)
                
        # Write clean data to the JSON output file
        with open(json_filepath, mode='w', encoding='utf-8') as json_file:
            json.dump(json_data, json_file, indent=4, ensure_ascii=False)
            
        print(f"Conversion complete. Output written to: {json_filepath}")
        
    except FileNotFoundError:
        print(f"Error: The file '{csv_filepath}' was not found.")
    except Exception as e:
        print(f"An error occurred during conversion: {e}")

# Example execution block
if __name__ == "__main__":
    # Update these paths as needed for your project structure
    input_csv = "program.csv"
    output_json = "program.json"
    
    convert_csv_to_json(input_csv, output_json)