# Code generated by Gemini 3.5 Flash
# Prompted by K. Martin to convert json schedule to qmd for Quarto
# 2026-07-29

import json
import os

def group_by_session(items):
    """
    Groups consecutive items chronologically by SESSION_TITLE and Session Chair.
    Items with no session title and no session chair are grouped together 
    with empty strings.
    """
    sessions = []
    for item in items:
        title = item['SESSION_TITLE']
        chair = item['Session Chair']
        
        if sessions and sessions[-1]['title'] == title and sessions[-1]['chair'] == chair:
            sessions[-1]['items'].append(item)
        else:
            sessions.append({
                'title': title,
                'chair': chair,
                'items': [item]
            })
    return sessions

def build_rsafrica_qmd(json_file_path, qmd_file_path):
    """
    Parses program.json and generates a styled Quarto markdown file (.qmd)
    aligned with the style structure of rseaa.org/rsaa25_program,
    dividing the schedule into session blocks with designated Session Chairs,
    while omitting headers for unscheduled/ungrouped session blocks.
    """
    if not os.path.exists(json_file_path):
        print(f"Error: {json_file_path} not found.")
        return

    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Standardize field text, strip spaces, and handle types
    for item in data:
        item['Paper ID'] = str(item.get('Paper ID', '')).strip()
        item['DAY'] = str(item.get('DAY', '')).strip()
        item['TRACK'] = str(item.get('TRACK', 'Single')).strip()
        item['SESSION_TITLE'] = str(item.get('SESSION_TITLE', '')).strip()
        item['Session Chair'] = str(item.get('Session Chair', '')).strip()
        item['START_TIME'] = str(item.get('START_TIME', '')).strip()
        item['END_TIME'] = str(item.get('END_TIME', '')).strip()
        item['CALC_DURATION'] = str(item.get('CALC_DURATION', '')).strip()
        item['Paper Title'] = str(item.get('Paper Title', '')).strip()
        item['Abstract'] = str(item.get('Abstract', '')).strip()
        item['Q5 (Presenter(s) Name)'] = str(item.get('Q5 (Presenter(s) Name)', '')).strip()
        item['Q6 (Presenter(s) Bio)'] = str(item.get('Q6 (Presenter(s) Bio)', '')).strip()
        item['Type'] = str(item.get('Type', '')).strip()

    # Filter items that are scheduled to a specific day
    scheduled_items = [item for item in data if item['DAY']]
    
    # Sort chronologically by Day, Start Time, and Track
    scheduled_items.sort(key=lambda x: (x['DAY'], x['START_TIME'], x['TRACK']))

    # Group scheduled items by Day
    days_group = {}
    for item in scheduled_items:
        day = item['DAY']
        if day not in days_group:
            days_group[day] = []
        days_group[day].append(item)

    # Date mapping matching the conference dates (August 25th to 28th)
    day_dates = {
        "1": "Tuesday 25 August",
        "2": "Wednesday 26 August",
        "3": "Thursday 27 August",
        "4": "Friday 28 August"
    }

    # Format-to-Label mapper
    type_labels = {
        "talk": "Presentation",
        "demo": "Demo/Showcase",
        "workshop": "Workshop",
        "panel": "Panel",
        "keynote": "Keynote",
        "welcoming": "Welcoming"
    }

    # Start Quarto front-matter configuration
    qmd_content = """---
title: "RSAfrica26 Conference Program"
subtitle: "1st Research Software Africa Conference"
author: "RSAfrica26 Organising Committee"
date: "2026-08-25"
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
    anchor-sections: true
---

::: {.callout-note}
### Timezone Notice
All times in this program are displayed in **South African Standard Time (SAST) / UTC +2**.
:::

## Program

"""

    for day in sorted(days_group.keys()):
        day_label = day_dates.get(day, f"Day {day}")
        qmd_content += f"## Day {day} – {day_label}\n\n"
        
        day_items = days_group[day]
        has_parallel = any(item['TRACK'] in ['Track A', 'Track B'] for item in day_items)

        if has_parallel:
            # Parallel tracks (Day 3) implemented via native Quarto tabsets
            qmd_content += "::: {.panel-tabset}\n\n"
            
            # Split items by Track
            tracks = {}
            for item in day_items:
                track_name = item['TRACK']
                if track_name not in tracks:
                    tracks[track_name] = []
                tracks[track_name].append(item)
                
            for track_name in sorted(tracks.keys()):
                qmd_content += f"### {track_name}\n\n"
                
                # Group items within this track into session blocks
                session_blocks = group_by_session(tracks[track_name])
                
                for session in session_blocks:
                    # Only render header and chair metadata if the session title is defined
                    if session['title']:
                        qmd_content += f"#### {session['title']}\n\n"
                        if session['chair']:
                            qmd_content += f"**Session Chair:** {session['chair']}\n\n"
                    
                    qmd_content += "| Time | Length | Presentation | Presenter(s) | Type |\n"
                    qmd_content += "|---|---|---|---|---|\n"
                    
                    for item in session['items']:
                        duration = f"{item['CALC_DURATION']} min" if item['CALC_DURATION'] else ""
                        presenter = item['Q5 (Presenter(s) Name)'] or item['Primary Contact Author Name'] or ""
                        presenter = presenter.replace('\n', ' & ')
                        label = type_labels.get(item['Type'].lower(), item['Type'].capitalize())
                        
                        paper_id = item['Paper ID']
                        linked_title = f"[{item['Paper Title']}](#paper-{paper_id})" if paper_id else item['Paper Title']
                        
                        qmd_content += f"| {item['START_TIME']}–{item['END_TIME']} | {duration} | {linked_title} | {presenter} | {label} |\n"
                    qmd_content += "\n"
                
                # Presentation details for the current track
                qmd_content += "#### Presentation Details\n\n"
                for item in tracks[track_name]:
                    label = type_labels.get(item['Type'].lower(), item['Type'].capitalize())
                    presenter = item['Q5 (Presenter(s) Name)'] or item['Primary Contact Author Name'] or ""
                    presenter = presenter.replace('\n', ' & ')
                    paper_id = item['Paper ID']
                    
                    anchor = f" {{#paper-{paper_id}}}" if paper_id else ""
                    qmd_content += f"##### {label}. Title: {item['Paper Title']}{anchor}\n\n"
                    
                    if presenter:
                        qmd_content += f"**Presenter Name**: {presenter}\n\n"
                    if item['Q6 (Presenter(s) Bio)']:
                        bio = item['Q6 (Presenter(s) Bio)'].replace('\n', '\n\n')
                        qmd_content += f"**Bio**: {bio}\n\n"
                    if item['Abstract']:
                        abstract = item['Abstract'].replace('\n', '\n\n')
                        qmd_content += f"**Abstract**: {abstract}\n\n"
                    qmd_content += "---\n\n"
            qmd_content += ":::\n\n" # Close tabset
            
        else:
            # Group items for single-track days into session blocks
            session_blocks = group_by_session(day_items)
            
            for session in session_blocks:
                # Only render header and chair metadata if the session title is defined
                if session['title']:
                    qmd_content += f"### {session['title']}\n\n"
                    if session['chair']:
                        qmd_content += f"**Session Chair:** {session['chair']}\n\n"
                
                qmd_content += "| Time | Length | Presentation | Presenter(s) | Type |\n"
                qmd_content += "|---|---|---|---|---|\n"
                
                for item in session['items']:
                    duration = f"{item['CALC_DURATION']} min" if item['CALC_DURATION'] else ""
                    presenter = item['Q5 (Presenter(s) Name)'] or item['Primary Contact Author Name'] or ""
                    presenter = presenter.replace('\n', ' & ')
                    label = type_labels.get(item['Type'].lower(), item['Type'].capitalize())
                    
                    paper_id = item['Paper ID']
                    linked_title = f"[{item['Paper Title']}](#paper-{paper_id})" if paper_id else item['Paper Title']
                    
                    qmd_content += f"| {item['START_TIME']}–{item['END_TIME']} | {duration} | {linked_title} | {presenter} | {label} |\n"
                qmd_content += "\n"
            
            # Presentation details for single-track days
            qmd_content += "### Presentation Details\n\n"
            for item in day_items:
                label = type_labels.get(item['Type'].lower(), item['Type'].capitalize())
                presenter = item['Q5 (Presenter(s) Name)'] or item['Primary Contact Author Name'] or ""
                presenter = presenter.replace('\n', ' & ')
                paper_id = item['Paper ID']
                
                anchor = f" {{#paper-{paper_id}}}" if paper_id else ""
                qmd_content += f"#### {label}. Title: {item['Paper Title']}{anchor}\n\n"
                
                if presenter:
                    qmd_content += f"**Presenter Name**: {presenter}\n\n"
                if item['Q6 (Presenter(s) Bio)']:
                    bio = item['Q6 (Presenter(s) Bio)'].replace('\n', '\n\n')
                    qmd_content += f"**Bio**: {bio}\n\n"
                if item['Abstract']:
                    abstract = item['Abstract'].replace('\n', '\n\n')
                    qmd_content += f"**Abstract**: {abstract}\n\n"
                qmd_content += "---\n\n"

    # Write .qmd file
    with open(qmd_file_path, 'w', encoding='utf-8') as f:
        f.write(qmd_content)
    print(f"Quarto Markdown successfully compiled to '{qmd_file_path}'.")

    # Generate companion CSS style rules to match the RSAA design
    css_content = """body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #111827;
    background-color: #fafafa;
}

h1, h2, h3, h4, h5 {
    color: #1e3a8a;
    font-weight: 700;
}

table {
    width: 100%;
    margin-bottom: 2rem;
    background-color: #ffffff;
    border: 1px solid #e5e7eb;
    border-collapse: collapse;
}

th, td {
    padding: 12px 15px;
    border: 1px solid #e5e7eb;
    text-align: left;
    vertical-align: top;
}

th {
    background-color: #eff6ff;
    color: #1e3a8a;
    font-weight: 600;
}

tr:nth-child(even) {
    background-color: #f9fafb;
}

/* Styled internal links matching RSAA's modern layout */
td a {
    color: #2563eb;
    text-decoration: none;
    font-weight: 500;
}

td a:hover {
    text-decoration: underline;
    color: #1d4ed8;
}

.callout-note {
    border-left-color: #2563eb !important;
}
"""
    with open("styles.css", "w", encoding="utf-8") as f:
        f.write(css_content)
    print("Stylesheet compiled to 'styles.css'.")

if __name__ == "__main__":
    build_rsafrica_qmd("output/program.json", "output/program.qmd")